CREATE TABLE products
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    price DECIMAL(9, 2) NOT NULL,
    CONSTRAINT products_pk PRIMARY KEY (id));

INSERT INTO products (name, price)
VALUES ('Beer', 2.50),
       ('Wine', 7.01),
       ('Ale', 3.00);