CREATE TABLE departments
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT departments_pk PRIMARY KEY (id));

CREATE TABLE employees
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    department_id INTEGER,
    CONSTRAINT employees_pk PRIMARY KEY (id),
    CONSTRAINT employee_department_fk FOREIGN KEY (department_id)
               REFERENCES departments (id));
