CREATE TABLE products
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT products_pk PRIMARY KEY (id));

CREATE TABLE chocolates
   (id INTEGER,
    calories DOUBLE PRECISION NOT NULL,
    CONSTRAINT chocolate_pk PRIMARY KEY (id),
    CONSTRAINT chocolate_fk FOREIGN KEY (id)
               REFERENCES products (id));

CREATE TABLE wines
   (id INTEGER,
    year INTEGER NOT NULL,
    CONSTRAINT wines_pk PRIMARY KEY (id),
    CONSTRAINT wines_fk FOREIGN KEY (id)
               REFERENCES products (id));