-- mapping the hierarchy using the single table strategy
CREATE TABLE issues
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    type CHAR NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    severity SMALLINT,
    target_version VARCHAR(50),
    CONSTRAINT issues_pk PRIMARY KEY (id));