CREATE TABLE students
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(70) NOT NULL,
    CONSTRAINT students_pk PRIMARY KEY (id));

CREATE TABLE professors
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(70) NOT NULL,
    CONSTRAINT professors_pk PRIMARY KEY (id));

CREATE TABLE enrollment
   (professor_id INTEGER,
    student_id INTEGER,
    CONSTRAINT enrollment_pk PRIMARY KEY (professor_id, student_id),
    CONSTRAINT enrollment_professor_fk FOREIGN KEY (professor_id)
               REFERENCES professors (id),
    CONSTRAINT enrollment_student_fk FOREIGN KEY (student_id)
               REFERENCES students (id));