CREATE TABLE nutrition
   (id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    calories      DOUBLE PRECISION NOT NULL,
    fat           DOUBLE PRECISION NOT NULL,
    carbohydrates DOUBLE PRECISION NOT NULL,
    CONSTRAINT nutrition_pk PRIMARY KEY (id));

CREATE TABLE products
   (id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(50) NOT NULL,
    price        DECIMAL(9, 2),
    nutrition_id INTEGER,
    CONSTRAINT products_pk PRIMARY KEY (id),
    CONSTRAINT products_nutrition_fk FOREIGN KEY (nutrition_id)
               REFERENCES nutrition (id));

CREATE TABLE product_weight
   (product_id INTEGER,
    netto DOUBLE PRECISION NOT NULL,
    brutto DOUBLE PRECISION NOT NULL,
    CONSTRAINT product_weight_pk PRIMARY KEY (product_id),
    CONSTRAINT product_weight_fk FOREIGN KEY (product_id)
               REFERENCES products (id));
