CREATE TABLE employees
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    -- personal phone number
    phone VARCHAR(20),
    CONSTRAINT employees_pk PRIMARY KEY (id));

CREATE TABLE departments
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    director INTEGER,
    -- a specific number for the phone in the director's office
    director_dept_phone VARCHAR(20) NOT NULL,
    accountant INTEGER,
    -- a specific number for the phone in the accountant's office
    accountant_dept_phone VARCHAR(20) NOT NULL,
    CONSTRAINT departments_pk PRIMARY KEY (id),
    CONSTRAINT departments_director_fk FOREIGN KEY (director)
               REFERENCES employees (id),
    CONSTRAINT deparments_accountant_fk FOREIGN KEY (accountant)
               REFERENCES employees (id));