CREATE TABLE persons
   (id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT persons_pk PRIMARY KEY (id));

CREATE TABLE phones
   (person_id INTEGER,
    number VARCHAR(20),
    CONSTRAINT phones_pk PRIMARY KEY (person_id, number),
    CONSTRAINT phones_fk FOREIGN KEY (person_id)
               REFERENCES persons (id));
